# Generated by Django 5.2.10 on 2026-03-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('participants', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], max_length=50)),
                ('diagnosis', models.CharField(choices=[('malignant', 'Malignant'), ('benign', 'Benign')], max_length=50)),
                ('confidence', models.FloatField()),
                ('source_label', models.CharField(max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='images.image')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('likert', 'Likert Scale'), ('slider', 'Slider'), ('binary', 'Binary'), ('numeric', 'Numeric'), ('free_text', 'Free Text')], max_length=50)),
                ('response_options', models.JSONField(blank=True, null=True)),
                ('scale_min', models.FloatField(blank=True, null=True)),
                ('scale_max', models.FloatField(blank=True, null=True)),
                ('scale_step', models.FloatField(blank=True, null=True)),
                ('condition_applicability', models.JSONField(default=list)),
                ('stage_location', models.CharField(choices=[('pre_trial', 'Pre-Trial'), ('initial_judgement', 'Initial Judgement'), ('post_feedback', 'Post-Feedback'), ('post_trial', 'Post-Trial'), ('end_of_study', 'End of Study')], max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.study')),
            ],
            options={
                'ordering': ['stage_location', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ground_truth', models.CharField(choices=[('malignant', 'Malignant'), ('benign', 'Benign')], max_length=50)),
                ('block_position', models.PositiveSmallIntegerField(db_index=True)),
                ('trial_position', models.PositiveSmallIntegerField(db_index=True)),
                ('is_practice', models.BooleanField(db_index=True, default=False)),
                ('is_catch_trial', models.BooleanField(default=False)),
                ('feedback_presented', models.JSONField(blank=True, null=True)),
                ('feedback_accuracy', models.CharField(choices=[('correct', 'Correct'), ('wrong', 'Wrong'), ('na', 'N/A')], default='na', max_length=50)),
                ('feedback_consensus_level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='study.condition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='images.image')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='participants.participantsession')),
            ],
            options={
                'ordering': ['-is_practice', 'block_position', 'trial_position'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.CharField(max_length=100)),
                ('response_timestamp', models.DateTimeField()),
                ('stage_location', models.CharField(choices=[('pre_trial', 'Pre-Trial'), ('initial_judgement', 'Initial Judgement'), ('post_feedback', 'Post-Feedback'), ('post_trial', 'Post-Trial'), ('end_of_study', 'End of Study')], db_index=True, max_length=50)),
                ('client_rt_ms', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='participants.participantsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='trials.question')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='trials.trial')),
            ],
            options={
                'unique_together': {('trial', 'question')},
            },
        ),
    ]
