# Generated by Django 5.2.10 on 2026-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='client_rt_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
