# Generated by Django 5.2.10 on 2026-03-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ground_truth', models.CharField(choices=[('malignant', 'Malignant'), ('benign', 'Benign')], max_length=50)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('is_practice', models.BooleanField(default=False)),
                ('is_catch_trial', models.BooleanField(default=False)),
                ('source_dataset', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_assignments', to='study.condition')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='images.image')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assignments', to='participants.participantsession')),
            ],
            options={
                'unique_together': {('image', 'participant')},
            },
        ),
    ]
