# Generated by Django 5.2.10 on 2026-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='external_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
