# Generated by Django 5.2.10 on 2026-03-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('baseline', 'Baseline'), ('human', 'Human'), ('human_ai', 'Human + AI'), ('ai', 'AI')], max_length=50)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('config_json', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('consent_html', models.TextField()),
                ('consent_version', models.CharField(max_length=20)),
                ('debrief_html', models.TextField()),
                ('debrief_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAgentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_agents', to='study.condition')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='study.study'),
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('study', 'name')},
        ),
    ]
