# Generated by Django 5.2.10 on 2026-03-11 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prolific_pid', models.CharField(db_index=True, max_length=50)),
                ('prolific_study_id', models.CharField(max_length=50)),
                ('prolific_session_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('django_session_key', models.CharField(db_index=True, max_length=50)),
                ('entry_timestamp', models.DateTimeField(auto_now_add=True)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('completion_status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('partial', 'Partial')], db_index=True, default='in_progress', max_length=50)),
                ('condition_order', models.JSONField(blank=True, null=True)),
                ('study_version', models.JSONField(blank=True, null=True)),
                ('excluded_inattentive', models.BooleanField(default=False)),
                ('attention_checks_failed', models.IntegerField(default=0)),
                ('median_trial_rt', models.FloatField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_sessions', to='study.study')),
            ],
        ),
        migrations.CreateModel(
            name='DebriefRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debrief_html', models.TextField()),
                ('debrief_version', models.CharField(max_length=20)),
                ('debrief_timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debrief_record', to='participants.participantsession')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_html', models.TextField()),
                ('consent_version', models.CharField(max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_record', to='participants.participantsession')),
            ],
        ),
        migrations.CreateModel(
            name='AttentionCheckResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.PositiveSmallIntegerField()),
                ('check_type', models.CharField(choices=[('imc', 'Instructional Manipulation Check'), ('catch_trial', 'Catch Trial'), ('infrequency', 'Infrequency Item')], max_length=50)),
                ('response_value', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_check_responses', to='participants.participantsession')),
            ],
        ),
        migrations.CreateModel(
            name='PostStudyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticed_feedback', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=50)),
                ('attention_to_feedback', models.IntegerField(blank=True, null=True)),
                ('influence_of_feedback', models.IntegerField(blank=True, null=True)),
                ('demand_awareness_response', models.TextField(blank=True)),
                ('demand_awareness_coded', models.IntegerField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_study_measure', to='participants.participantsession')),
            ],
        ),
        migrations.CreateModel(
            name='PreStudyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_training_level', models.CharField(choices=[('undergraduate', 'Undergraduate medical / nursing / radiography student'), ('postgraduate', 'Postgraduate / junior doctor / resident'), ('qualified_nurse', 'Qualified nurse or allied health professional'), ('qualified_doctor', 'Qualified doctor (non-specialist)'), ('radiologist', 'Radiologist or specialist with imaging experience')], max_length=50)),
                ('ai_trust_pre_score', models.FloatField(blank=True, null=True)),
                ('ai_trust_items', models.JSONField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_study_measure', to='participants.participantsession')),
            ],
        ),
    ]
